spring:
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://database-foorrng.cpcuiu0mwkgs.ap-northeast-2.rds.amazonaws.com:3306/foorrng?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: foorrng
#    password: foorrng205
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: wd29684280$$

  # Multipart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # JPA
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

# Cloud
cloud:
  aws:
    credentials:
      access-key: AKIASUV4IGKSFJPD557V
      secret-key: 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
    s3:
      bucket: foorrng
    region:
      ap-northeast-2
    stack:
      auto: false