spring:
  # git ignore 테스트
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foorrng?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ssafy
  #    url: jdbc:mysql://database-foorrng.cpcuiu0mwkgs.ap-northeast-2.rds.amazonaws.com:3306/foorrng?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
  #    username: foorrng
  #    password: foorrng205
  # Multipart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # JPA
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

# Cloud
cloud:
  aws:
    credentials:
      access-key: AKIASUV4IGKSFJPD557V
      secret-key: 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
    s3:
      bucket: elasticbeanstalk-ap-northeast-2-181857170084
    region:
      ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com.example: DEBUG

jwt:
  header:
    - Authorization
    - Refresh-Token
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

externalService:
  apiKey: q9XV9UvePtF1od74YygO2yzyXpdItr0hi7MXezIum87O6ydsHSfrb60yVAUSav6tJVOEiSNZMXsgEanOStUEIQ==
